### ISSUE TITLE
There should be a separate branch for v8.7

### ISSUE THREAD

**Issue by JasonGross** [Karmaki/coq-dpdgraph#32]
Please branch `coq-trunk` to `coq-v8.7`, and drop the `open API` lines from the `v8.7` branch (or I can make a PR that does that, if you create the branch).

**Comment by Karmaki** [comment]
I have added the branch you asked for, but since I don't understand precisely which `open` you want me to remove, and since I don't have time to test it now, I prefer that you do a PR. Thanks.

Moreover, you will probably also which to change the `.travis.yml` file on this branch to select the coq version, won't you?

**Comment by JasonGross** [comment]
Thanks!  I've made https://github.com/Karmaki/coq-dpdgraph/pull/33, and updated `.travis.yml`---good catch!

**Comment by Karmaki** [comment]
I have added the branch you asked for, but since I don't understand precisely which `open` you want me to remove, and since I don't have time to test it now, I prefer that you do a PR. Thanks.

Moreover, you will probably also which to change the `.travis.yml` file on this branch to select the coq version, won't you?
